# conda env create --file environment.yml
# conda env update --file environment.yml
name: wio
channels:
  - conda-forge
  - defaults
dependencies:
  - django
  - django-extensions
  - pydot
  - python
